name: The Experience Firm
favicon: null
layout_spectrum: 0.7987708027940243
typography_spectrum: 0.979020195780322
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8399111570324749
  lightness: 0.8531161844730377
  saturation: 0.9969569921959192
  rhythmicContrast: 0.4730985655914992
purpose: []
