name: The Experience Firm
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: A Word of Mouth Marketing Co
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#a9aba1'
    - '#ffaf00'
    - '#981800'
    - '#ffee00'
  brandStrength: 0.8399111570324749
  lightness: 0.8531161844730377
  saturation: 0.9969569921959192
  rhythmicContrast: 0.4730985655914992
purpose: []
